-- Query base para histórico de pedidos no Plenus (últimos 12 meses)
-- Parâmetros esperados:
--   @cd_pessoa   -> código do cliente logado (CD_PESSOA)
--   @data_inicio -> data inicial do recorte (ex.: DATEADD(MONTH, -12, GETDATE()))

DECLARE @cd_pessoa INT = 8294;
DECLARE @data_inicio DATE = DATEADD(MONTH, -12, GETDATE());

-- Pedidos efetivados / comprados (em produção ou finalizados)
SELECT
    PEDIDO.CD_EMPRESA,
    PEDIDO.CD_DOCUMENTO,
    PEDIDO.NR_COMPL,
    PEDIDO.DT_EMISSAO,
    PEDIDO.CD_PESSOA,
    PEDIDO.NM_PESSOA,
    PEDIDO.CD_NATUREZA,
    PEDIDO.CD_TIPO,
    PEDIDO.ID_STATUS,
    PEDIDO.CD_ETAPA,
    PEDIDO.DS_ATRIBUTO8 AS CD_VENDEDOR,
    VENDEDOR.NM_PESSOA AS NM_VENDEDOR,
    ITEM.CD_ITEM,
    ITEM.DS_ITEM,
    ITEM.CD_PRODUTO,
    ITEM.CD_OPERACAO,
    ITEM.VL_QUANTIDADE,
    ITEM.VL_TOTALITEM,
    PRODUTO.DS_PRODUTO,
    PRODUTO.DS_REFERENCIA,
    PRODUTO.CD_MARCA,
    PRODUTO.CD_FAMILIA,
    PRODUTO.CD_GRUPO,
    PRODUTO.CD_SUBGRUPO,
    PRODUTO.CD_CLASSFISCAL,
    PRODUTO.CD_CATEGORIA,
    PRODUTO.CD_MATERIAL,
    PRODUTO.CD_NCM,
    PRODUTO.VL_PESOLIQUIDO,
    PRODUTO.CD_FABRICANTE
FROM MVPE_PEDIDO AS PEDIDO
INNER JOIN MVPE_PEDIDOITEM AS ITEM
    ON PEDIDO.CD_EMPRESA = ITEM.CD_EMPRESA
    AND PEDIDO.NR_COMPL = ITEM.NR_COMPL
    AND PEDIDO.CD_DOCUMENTO = ITEM.CD_DOCUMENTO
INNER JOIN MMPR_PRODUTO AS PRODUTO
    ON PEDIDO.CD_EMPRESA = PRODUTO.CD_EMPRESA
    AND ITEM.CD_PRODUTO = PRODUTO.CD_PRODUTO
LEFT JOIN MBAD_PESSOA AS VENDEDOR
    ON VENDEDOR.CD_PESSOA = PEDIDO.DS_ATRIBUTO8
WHERE PEDIDO.CD_PESSOA = @cd_pessoa
  AND PEDIDO.DT_EMISSAO >= @data_inicio
  AND PEDIDO.CD_TIPO IN (1, 2, 8, 10, 11)
  AND PEDIDO.ID_STATUS IN (1, 2)
  AND PEDIDO.CD_ETAPA IN (2, 7, 8, 9, 10)
  AND PRODUTO.CD_PRODCONFIG IS NOT NULL
  AND PRODUTO.CD_PRODCONFIG <> 'IA'
  AND PRODUTO.DS_REFERENCIA NOT LIKE '%2.WS%'
  AND PRODUTO.DS_REFERENCIA NOT LIKE 'MS.%'
ORDER BY PEDIDO.DT_EMISSAO DESC;

-- Pedidos em aberto / em andamento (caso queira usar para insights adicionais)
SELECT
    PEDIDO.CD_EMPRESA,
    PEDIDO.CD_DOCUMENTO,
    PEDIDO.NR_COMPL,
    PEDIDO.DT_EMISSAO,
    PEDIDO.CD_PESSOA,
    PEDIDO.NM_PESSOA,
    PEDIDO.CD_NATUREZA,
    PEDIDO.CD_TIPO,
    PEDIDO.ID_STATUS,
    PEDIDO.CD_ETAPA,
    PEDIDO.DS_ATRIBUTO8 AS CD_VENDEDOR,
    VENDEDOR.NM_PESSOA AS NM_VENDEDOR,
    ITEM.CD_ITEM,
    ITEM.DS_ITEM,
    ITEM.CD_PRODUTO,
    ITEM.CD_OPERACAO,
    ITEM.VL_QUANTIDADE,
    ITEM.VL_TOTALITEM,
    PRODUTO.DS_PRODUTO,
    PRODUTO.DS_REFERENCIA,
    PRODUTO.CD_MARCA,
    PRODUTO.CD_FAMILIA,
    PRODUTO.CD_GRUPO,
    PRODUTO.CD_SUBGRUPO,
    PRODUTO.CD_CLASSFISCAL,
    PRODUTO.CD_CATEGORIA,
    PRODUTO.CD_MATERIAL,
    PRODUTO.CD_NCM,
    PRODUTO.VL_PESOLIQUIDO,
    PRODUTO.CD_FABRICANTE
FROM MVPE_PEDIDO AS PEDIDO
INNER JOIN MVPE_PEDIDOITEM AS ITEM
    ON PEDIDO.CD_EMPRESA = ITEM.CD_EMPRESA
    AND PEDIDO.NR_COMPL = ITEM.NR_COMPL
    AND PEDIDO.CD_DOCUMENTO = ITEM.CD_DOCUMENTO
INNER JOIN MMPR_PRODUTO AS PRODUTO
    ON PEDIDO.CD_EMPRESA = PRODUTO.CD_EMPRESA
    AND ITEM.CD_PRODUTO = PRODUTO.CD_PRODUTO
LEFT JOIN MBAD_PESSOA AS VENDEDOR
    ON VENDEDOR.CD_PESSOA = PEDIDO.DS_ATRIBUTO8
WHERE PEDIDO.CD_PESSOA = @cd_pessoa
  AND PEDIDO.DT_EMISSAO >= @data_inicio
  AND PEDIDO.CD_TIPO IN (1, 2, 8, 10, 11)
  AND PEDIDO.ID_STATUS IN (0, 1, 5)
  AND PEDIDO.CD_ETAPA IN (1, 16, 3, 4, 5, 11, 12, 13, 15, 17, 18, 19, 2, 8)
    AND PRODUTO.CD_PRODCONFIG IS NOT NULL
  AND PRODUTO.CD_PRODCONFIG <> 'IA'
  AND PRODUTO.DS_REFERENCIA NOT LIKE '%2.WS%'
  AND PRODUTO.DS_REFERENCIA NOT LIKE 'MS.%'
ORDER BY PEDIDO.DT_EMISSAO DESC;
